### ISSUE TITLE
Out of memory on player.connect()

### ISSUE THREAD

**Issue by Jade3375** [Lavaclient/lavaclient#18]
not sure if i did something wrong but any time i try connect a player to a channel i get an Out of memory error 

<rejected> Error: Out of memory
      at Object.func (C:\Users\Gamer\Desktop\code\Asuna-Eris\node_modules\eris\lib\gateway\Shard.js:1999:52)
      at Bucket.check (C:\Users\Gamer\Desktop\code\Asuna-Eris\node_modules\eris\lib\util\Bucket.js:61:22)
      at Bucket.queue (C:\Users\Gamer\Desktop\code\Asuna-Eris\node_modules\eris\lib\util\Bucket.js:41:14)
      at Shard.sendWS (C:\Users\Gamer\Desktop\code\Asuna-Eris\node_modules\eris\lib\gateway\Shard.js:2008:31)
      at Manager.send (C:\Users\Gamer\Desktop\code\Asuna-Eris\src\asuna\functions\lavalink\index.js:22:36)
      at Player.connect (C:\Users\Gamer\Desktop\code\Asuna-Eris\node_modules\lavaclient\dist\structures\Player.js:48:35)

**Comment by MeLike2D** [comment]
I have never encountered this issue... can you show me your send function?

**Comment by Jade3375** [comment]
send: (id, data) => {
                let guild = this.client.bot.guilds.get(id);
                if(guild) guild.shard.sendWS(data.op, data.d, false);
                return
            }

ive tried with / without the arrow function same issue every time ive followed the docs for everything

**Comment by MeLike2D** [comment]
how much memory does your system have?

**Comment by Jade3375** [comment]
16GB

**Comment by MeLike2D** [comment]
I have no clue what is causing this... this might be an Eris issue. I have an Eris bot with a similar configuration and it works completely fine, I doubt this is an issue with your code

**Comment by MeLike2D** [comment]
you could try logging the data in the send function, that might help

**Comment by Jade3375** [comment]
yeah ill try and let u know what i get
